import uuid

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from ..auth.dependencies import get_current_user, get_scoped_db, require_role
from ..models import User
from ..schemas.survey import (
    SurveyListResponse,
    SurveyOut,
    SurveyReviewUpdate,
    SurveySyncRequest,
    SurveySyncResponse,
)
from ..services import surveys as surveys_service

router = APIRouter(prefix="/surveys", tags=["surveys"])


@router.post("/sync", response_model=SurveySyncResponse)
def sync_surveys(
    payload: SurveySyncRequest,
    db: Session = Depends(get_scoped_db),
    current_user: User = Depends(get_current_user),
):
    """Rule 5: survey_id is client-generated by the field PWA before
    connectivity exists; this upserts by that id, so a retried sync (the
    request succeeded but the response was lost, and the app retries) is a
    no-op, never a duplicate. Batched — one bad item doesn't fail the rest,
    each is applied in its own SAVEPOINT so a failure rolls back only that
    item (services/surveys.py's sync_surveys)."""
    synced, errors = surveys_service.sync_surveys(db, payload.surveys, officer_id=current_user.user_id)
    return SurveySyncResponse(synced=synced, errors=errors)


@router.get("", response_model=SurveyListResponse)
def list_surveys(
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
    db: Session = Depends(get_scoped_db),
):
    """RLS on surveys (Backend Schema §7) scopes this to a field_officer's
    assigned zones the same way GET /zones does."""
    items, total = surveys_service.list_surveys(db, limit=limit, offset=offset)
    return SurveyListResponse(items=items, count=total, limit=limit, offset=offset)


@router.patch("/{survey_id}/review", response_model=SurveyOut)
def review_survey(
    survey_id: uuid.UUID,
    payload: SurveyReviewUpdate,
    db: Session = Depends(get_scoped_db),
    current_user: User = Depends(get_current_user),
    _: object = Depends(require_role("sdma_official")),
):
    if payload.review_status not in ("approved", "flagged"):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="review_status must be 'approved' or 'flagged'")
    survey = surveys_service.update_review_status(db, survey_id, payload.review_status, reviewer_id=current_user.user_id)
    if survey is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="survey not found")
    return survey
